/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import forme_gost.FormaNoviGost;
import forme_gost.FormaPretragaGosta;
import forme_usluga.FormaNovaUsluga;
import forme_usluga.FormaPretragaUsluga;
import kontroler.KlijentKontroler;
import domen.Gost;
import domen.Rezervacija;
import domen.StavkaRezervacije;
import domen.Usluga;
import domen.Zaposleni;
import forme_rezervacija.FormaPretragaRezervacije;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modeli.ModelTabeleStavkeRezervacije;
import sesija.Sesija;

/**
 *
 * @author vanja
 */
public class GlavnaForma extends javax.swing.JFrame {

    private Zaposleni ulogovani;
    private int brojDana;
    private double cenaPoDanu;
    private double ukupanIznos;

    /**
     * Creates new form MainForm
     */
    public GlavnaForma() {
        initComponents();
        setLocationRelativeTo(null);
        this.ulogovani = Sesija.getInstance().getUlogovani();
        lblUlogovani.setText("Ulogovani zaposleni: " + ulogovani);
        setTitle("Klijentska forma");
        Sesija.getInstance().setGf(this);
        popuniGoste();
        popuniUsluge();
        txtBrojDana.setEditable(false);
        txtIznos.setEditable(false);
        tblStavke.setModel(new ModelTabeleStavkeRezervacije());
        txtBrojDana.setText("");
        cmbUsluga.setEnabled(false);
        btnObrisiStavku.setEnabled(false);
        btnDodajStavku.setEnabled(false);
        lblUkupanIznos.setText("0.00");
        txtIznos.setText("0.00");
        ukupanIznos = 0;
        brojDana = 0;

        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                int odgovor = JOptionPane.showConfirmDialog(
                        null,
                        "Da li ste sigurni da zelite da se odjavite?",
                        "Konfirmacija",
                        JOptionPane.YES_NO_OPTION
                );

                if (odgovor == JOptionPane.YES_OPTION) {
                    try {
                        KlijentKontroler.getInstance().odjava(ulogovani);
                        System.exit(0);
                    } catch (Exception ex) {
                        Logger.getLogger(GlavnaForma.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUlogovani = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnIzracunaj = new javax.swing.JButton();
        cmbGost = new javax.swing.JComboBox();
        cmbSoba = new javax.swing.JComboBox();
        txtDatumPrijave = new javax.swing.JFormattedTextField();
        txtDatumOdjave = new javax.swing.JFormattedTextField();
        txtBrojDana = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmbUsluga = new javax.swing.JComboBox();
        txtIznos = new javax.swing.JTextField();
        btnDodajStavku = new javax.swing.JButton();
        btnObrisiStavku = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStavke = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNapomena = new javax.swing.JTextArea();
        btnSacuvaj = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        lblUkupanIznos = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCenaPoDanu = new javax.swing.JFormattedTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        miNoviGost = new javax.swing.JMenuItem();
        miPretragaGosta = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        miNovaUsluga = new javax.swing.JMenuItem();
        miPretragaUsluge = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        miPretragaRezervacije = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        miOdjava = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUlogovani.setText("Ulogovani");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Rezervacija"));

        jLabel1.setText("Datum prijave:");

        jLabel2.setText("Datum odjave:");

        jLabel3.setText("Broj dana:");

        jLabel4.setText("Gost:");

        jLabel5.setText("Soba:");

        btnIzracunaj.setText("Izracunaj broj dana");
        btnIzracunaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzracunajActionPerformed(evt);
            }
        });

        cmbGost.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbSoba.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A1", "A2", "A3", "B1", "B2", "B3" }));

        txtDatumPrijave.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd.MM.yyyy"))));
        txtDatumPrijave.setText("15.03.2026");
        txtDatumPrijave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDatumPrijaveKeyReleased(evt);
            }
        });

        txtDatumOdjave.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd.MM.yyyy"))));
        txtDatumOdjave.setText("25.03.2026");
        txtDatumOdjave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDatumOdjaveKeyReleased(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Stavke rezervacije"));

        jLabel6.setText("Usluga:");

        jLabel7.setText("Iznos (din):");

        cmbUsluga.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbUsluga.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbUslugaItemStateChanged(evt);
            }
        });

        btnDodajStavku.setText("Dodaj stavku");
        btnDodajStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajStavkuActionPerformed(evt);
            }
        });

        btnObrisiStavku.setText("Obrisi stavku");
        btnObrisiStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiStavkuActionPerformed(evt);
            }
        });

        tblStavke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblStavke);

        jLabel10.setText("Napomena:");

        txtNapomena.setColumns(20);
        txtNapomena.setRows(5);
        jScrollPane2.setViewportView(txtNapomena);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIznos))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(29, 29, 29)
                                .addComponent(cmbUsluga, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnDodajStavku, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnObrisiStavku, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbUsluga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtIznos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDodajStavku)
                    .addComponent(btnObrisiStavku))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnSacuvaj.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnSacuvaj.setText("Sacuvaj rezervaciju");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        jLabel8.setText("Ukupan iznos:");

        lblUkupanIznos.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblUkupanIznos.setText("0.00");

        jLabel9.setText("Cena po danu:");

        txtCenaPoDanu.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtCenaPoDanu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCenaPoDanuKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel8)
                                .addGap(37, 37, 37)
                                .addComponent(lblUkupanIznos)))
                        .addGap(16, 16, 16))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(76, 76, 76)
                                        .addComponent(cmbSoba, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(79, 79, 79)
                                        .addComponent(cmbGost, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel9))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnIzracunaj, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .addComponent(txtBrojDana, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDatumOdjave)
                            .addComponent(txtDatumPrijave)
                            .addComponent(txtCenaPoDanu, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDatumPrijave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDatumOdjave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(37, 37, 37)
                .addComponent(btnIzracunaj, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtBrojDana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblUkupanIznos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbGost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbSoba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtCenaPoDanu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu6.setText("Gost");

        miNoviGost.setText("Novi gost");
        miNoviGost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNoviGostActionPerformed(evt);
            }
        });
        jMenu6.add(miNoviGost);

        miPretragaGosta.setText("Pretraga gosta");
        miPretragaGosta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPretragaGostaActionPerformed(evt);
            }
        });
        jMenu6.add(miPretragaGosta);

        jMenuBar1.add(jMenu6);

        jMenu8.setText("Usluga");

        miNovaUsluga.setText("Nova usluga");
        miNovaUsluga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNovaUslugaActionPerformed(evt);
            }
        });
        jMenu8.add(miNovaUsluga);

        miPretragaUsluge.setText("Pretraga usluge");
        miPretragaUsluge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPretragaUslugeActionPerformed(evt);
            }
        });
        jMenu8.add(miPretragaUsluge);

        jMenuBar1.add(jMenu8);

        jMenu9.setText("Rezervacija");

        miPretragaRezervacije.setText("Pretraga rezervacije");
        miPretragaRezervacije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPretragaRezervacijeActionPerformed(evt);
            }
        });
        jMenu9.add(miPretragaRezervacije);

        jMenuBar1.add(jMenu9);

        jMenu7.setText("Odjava");

        miOdjava.setText("Odjavi se");
        miOdjava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miOdjavaActionPerformed(evt);
            }
        });
        jMenu7.add(miOdjava);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUlogovani)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUlogovani)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miNoviGostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNoviGostActionPerformed
        new FormaNoviGost(this, true).setVisible(true);
    }//GEN-LAST:event_miNoviGostActionPerformed

    private void miPretragaGostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPretragaGostaActionPerformed
        new FormaPretragaGosta(this, true).setVisible(true);
    }//GEN-LAST:event_miPretragaGostaActionPerformed

    private void miOdjavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miOdjavaActionPerformed
        int rezultat = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da "
                + "se odjavite?", "Konfirmacija", JOptionPane.YES_NO_OPTION);

        if (rezultat == JOptionPane.NO_OPTION) {
            return;
        }

        if (rezultat == JOptionPane.YES_OPTION) {
            try {
                KlijentKontroler.getInstance().odjava(ulogovani);
                new LoginForma().setVisible(true);
                Sesija.getInstance().setUlogovani(null);
                this.dispose();
            } catch (Exception ex) {
                Logger.getLogger(GlavnaForma.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_miOdjavaActionPerformed

    private void miNovaUslugaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNovaUslugaActionPerformed
        new FormaNovaUsluga(this, true).setVisible(true);
    }//GEN-LAST:event_miNovaUslugaActionPerformed

    private void miPretragaUslugeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPretragaUslugeActionPerformed
        new FormaPretragaUsluga(this, true).setVisible(true);
    }//GEN-LAST:event_miPretragaUslugeActionPerformed

    private void miPretragaRezervacijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPretragaRezervacijeActionPerformed
        new FormaPretragaRezervacije(this, true).setVisible(true);
    }//GEN-LAST:event_miPretragaRezervacijeActionPerformed

    private void btnIzracunajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzracunajActionPerformed

        ModelTabeleStavkeRezervacije mt = (ModelTabeleStavkeRezervacije) tblStavke.getModel();
        mt.getLista().clear();
        mt.fireTableDataChanged();

        if (txtDatumPrijave.getText().isEmpty() || txtDatumOdjave.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Morate popuniti datum prijave i datum odjave!");
            return;
        }

        try {
            SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
            Date datumPrijave = sdf.parse(txtDatumPrijave.getText());
            Date datumOdjave = sdf.parse(txtDatumOdjave.getText());

            if (datumPrijave.after(datumOdjave) || datumPrijave.equals(datumOdjave)) {
                JOptionPane.showMessageDialog(this, "Datum prijave mora biti pre datuma odjave!");
                return;
            }

            if (datumPrijave.before(new Date()) || datumPrijave.equals(datumOdjave)) {
                JOptionPane.showMessageDialog(this, "Datum prijave mora biti u buducnosti!");
                return;
            }

            long razlikaMilisekunde = datumOdjave.getTime() - datumPrijave.getTime();
            long razlika = TimeUnit.DAYS.convert(razlikaMilisekunde, TimeUnit.MILLISECONDS);

            txtBrojDana.setText(String.valueOf(razlika));

            brojDana = Integer.parseInt(txtBrojDana.getText());

            cmbUsluga.setEnabled(true);
            btnObrisiStavku.setEnabled(true);
            btnDodajStavku.setEnabled(true);
            
                
            cenaPoDanu = Double.parseDouble(txtCenaPoDanu.getText());

            ukupanIznos = cenaPoDanu * brojDana;

            lblUkupanIznos.setText(String.valueOf(ukupanIznos) + "din");

            Usluga usluga = (Usluga) cmbUsluga.getSelectedItem();
            if (!txtBrojDana.getText().isEmpty()) {
                txtIznos.setText(String.valueOf(usluga.getCena() * brojDana));
            }

        } catch (Exception ex) {
            Logger.getLogger(GlavnaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnIzracunajActionPerformed

    private void txtDatumPrijaveKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDatumPrijaveKeyReleased
        txtBrojDana.setText("");
        ModelTabeleStavkeRezervacije mt = (ModelTabeleStavkeRezervacije) tblStavke.getModel();
        mt.getLista().clear();
        mt.fireTableDataChanged();
        cmbUsluga.setEnabled(false);
        btnObrisiStavku.setEnabled(false);
        btnDodajStavku.setEnabled(false);
        lblUkupanIznos.setText("0.00");
        txtIznos.setText("0.00");
        ukupanIznos = 0;
        brojDana = 0;
    }//GEN-LAST:event_txtDatumPrijaveKeyReleased

    private void txtDatumOdjaveKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDatumOdjaveKeyReleased
        txtBrojDana.setText("");
        ModelTabeleStavkeRezervacije mt = (ModelTabeleStavkeRezervacije) tblStavke.getModel();
        mt.getLista().clear();
        mt.fireTableDataChanged();
        cmbUsluga.setEnabled(false);
        btnObrisiStavku.setEnabled(false);
        btnDodajStavku.setEnabled(false);
        lblUkupanIznos.setText("0.00");
        txtIznos.setText("0.00");
        ukupanIznos = 0;
        brojDana = 0;
    }//GEN-LAST:event_txtDatumOdjaveKeyReleased

    private void cmbUslugaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbUslugaItemStateChanged
        if (cmbUsluga.getSelectedItem() != null) {
            Usluga usluga = (Usluga) cmbUsluga.getSelectedItem();
            if (!txtBrojDana.getText().isEmpty()) {
                txtIznos.setText(String.valueOf(usluga.getCena() * brojDana));
            }
        }
    }//GEN-LAST:event_cmbUslugaItemStateChanged

    private void btnDodajStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajStavkuActionPerformed

        Usluga usluga = (Usluga) cmbUsluga.getSelectedItem();
        double iznos = Double.parseDouble(txtIznos.getText());
        String napomena = txtNapomena.getText();

        StavkaRezervacije sr = new StavkaRezervacije(null, -1, napomena,
                usluga.getCena(), iznos, brojDana, usluga);

        ModelTabeleStavkeRezervacije mt = (ModelTabeleStavkeRezervacije) tblStavke.getModel();

        if (mt.postojiUsluga(usluga)) {
            JOptionPane.showMessageDialog(this, "Vec ste uneli ovu uslugu!");
            return;
        }

        mt.dodajStavku(sr);

        ukupanIznos = mt.vratiUkupanIznos() + cenaPoDanu * brojDana;
        lblUkupanIznos.setText(String.valueOf(ukupanIznos) + "din");
    }//GEN-LAST:event_btnDodajStavkuActionPerformed

    private void btnObrisiStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiStavkuActionPerformed

        int red = tblStavke.getSelectedRow();

        if (red >= 0) {
            ModelTabeleStavkeRezervacije mt = (ModelTabeleStavkeRezervacije) tblStavke.getModel();
            mt.obrisiStavku(red);

            ukupanIznos = mt.vratiUkupanIznos() + cenaPoDanu * brojDana;
            lblUkupanIznos.setText(String.valueOf(ukupanIznos) + "din");
        }
    }//GEN-LAST:event_btnObrisiStavkuActionPerformed

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed

        try {
            if (txtBrojDana.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Morate izracunati broj dana!");
                return;
            }

            Gost gost = (Gost) cmbGost.getSelectedItem();
            String soba = (String) cmbSoba.getSelectedItem();
            SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
            Date datumPrijave = sdf.parse(txtDatumPrijave.getText());
            Date datumOdjave = sdf.parse(txtDatumOdjave.getText());

            ModelTabeleStavkeRezervacije mt = (ModelTabeleStavkeRezervacije) tblStavke.getModel();

            Rezervacija r = new Rezervacija(-1, datumPrijave, datumOdjave, ukupanIznos,
                    soba, gost, ulogovani, mt.getLista());

            KlijentKontroler.getInstance().dodajRezervaciju(r);
            txtBrojDana.setText("");
            mt.getLista().clear();
            mt.fireTableDataChanged();
            cmbUsluga.setEnabled(false);
            btnObrisiStavku.setEnabled(false);
            btnDodajStavku.setEnabled(false);
            lblUkupanIznos.setText("0.00");
            txtIznos.setText("0.00");
            txtDatumPrijave.setText("");
            txtDatumOdjave.setText("");
            ukupanIznos = 0;
            brojDana = 0;
            JOptionPane.showMessageDialog(this, "Uspesno sacuvana rezervacija!");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            // Logger.getLogger(GlavnaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSacuvajActionPerformed

    private void txtCenaPoDanuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCenaPoDanuKeyReleased
        txtBrojDana.setText("");
        ModelTabeleStavkeRezervacije mt = (ModelTabeleStavkeRezervacije) tblStavke.getModel();
        mt.getLista().clear();
        mt.fireTableDataChanged();
        cmbUsluga.setEnabled(false);
        btnObrisiStavku.setEnabled(false);
        btnDodajStavku.setEnabled(false);
        lblUkupanIznos.setText("0.00");
        txtIznos.setText("0.00");
        ukupanIznos = 0;
        brojDana = 0;
    }//GEN-LAST:event_txtCenaPoDanuKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajStavku;
    private javax.swing.JButton btnIzracunaj;
    private javax.swing.JButton btnObrisiStavku;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox cmbGost;
    private javax.swing.JComboBox cmbSoba;
    private javax.swing.JComboBox cmbUsluga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblUkupanIznos;
    private javax.swing.JLabel lblUlogovani;
    private javax.swing.JMenuItem miNovaUsluga;
    private javax.swing.JMenuItem miNoviGost;
    private javax.swing.JMenuItem miOdjava;
    private javax.swing.JMenuItem miPretragaGosta;
    private javax.swing.JMenuItem miPretragaRezervacije;
    private javax.swing.JMenuItem miPretragaUsluge;
    private javax.swing.JTable tblStavke;
    private javax.swing.JTextField txtBrojDana;
    private javax.swing.JFormattedTextField txtCenaPoDanu;
    private javax.swing.JFormattedTextField txtDatumOdjave;
    private javax.swing.JFormattedTextField txtDatumPrijave;
    private javax.swing.JTextField txtIznos;
    private javax.swing.JTextArea txtNapomena;
    // End of variables declaration//GEN-END:variables

    public void popuniGoste() {
        try {
            ArrayList<Gost> gosti = KlijentKontroler.getInstance().pretragaGosta();

            cmbGost.removeAllItems();

            for (Gost gost : gosti) {
                cmbGost.addItem(gost);
            }
        } catch (Exception ex) {
            Logger.getLogger(GlavnaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void popuniUsluge() {
        try {
            ArrayList<Usluga> usluge = KlijentKontroler.getInstance().pretragaUsluge();

            cmbUsluga.removeAllItems();

            for (Usluga usluga : usluge) {
                cmbUsluga.addItem(usluga);
            }
        } catch (Exception ex) {
            Logger.getLogger(GlavnaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
