/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme_rezervacija;

import kontroler.KlijentKontroler;
import domen.Rezervacija;
import domen.StavkaRezervacije;
import domen.Usluga;
import forme.GlavnaForma;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import modeli.ModelTabeleStavkeRezervacije;

/**
 *
 * @author vanja
 */
public class FormaDetaljiRezervacije extends javax.swing.JDialog {

    private Rezervacija r;
    private int brojDana;
    private double cenaPoDanu;
    private double ukupanIznos;

    public FormaDetaljiRezervacije(JDialog parent, boolean modal, Rezervacija r) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Detalji rezervacije");
        this.r = r;
        cmbGost.getModel().setSelectedItem(r.getGost());
        cmbGost.setEnabled(false);
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
        txtDatumPrijave.setText(sdf.format(r.getDatumPrijave()));
        txtDatumOdjave.setText(sdf.format(r.getDatumOdjave()));
        popuniUsluge();
        ukupanIznos = r.getIznos();
        lblUkupanIznos.setText(ukupanIznos + "din");
        tblStavke.setModel(new ModelTabeleStavkeRezervacije(r.getStavkeRezervacije()));

        txtBrojDana.setText("");
        txtBrojDana.setEditable(false);
        txtIznos.setEditable(false);
        cmbUsluga.setEnabled(false);
        btnObrisiStavku.setEnabled(false);
        btnDodajStavku.setEnabled(false);

        if (!r.getDatumPrijave().after(new Date())) {
            txtDatumPrijave.setEditable(false);
            txtDatumOdjave.setEditable(false);
            txtNapomena.setEditable(false);
            btnIzmeni.setEnabled(false);
            btnObrisi.setEnabled(false);
            cmbSoba.setEnabled(false);
            btnIzracunaj.setEnabled(false);
            JOptionPane.showMessageDialog(this, "Datum prijave ove rezervacije je prosao!");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnIzracunaj = new javax.swing.JButton();
        cmbGost = new javax.swing.JComboBox();
        cmbSoba = new javax.swing.JComboBox();
        txtDatumPrijave = new javax.swing.JFormattedTextField();
        txtDatumOdjave = new javax.swing.JFormattedTextField();
        txtBrojDana = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmbUsluga = new javax.swing.JComboBox();
        txtIznos = new javax.swing.JTextField();
        btnDodajStavku = new javax.swing.JButton();
        btnObrisiStavku = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStavke = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNapomena = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        lblUkupanIznos = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCenaPoDanu = new javax.swing.JFormattedTextField();
        btnIzmeni = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        btnZatvori = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Rezervacija"));

        jLabel1.setText("Datum prijave:");

        jLabel2.setText("Datum odjave:");

        jLabel3.setText("Broj dana:");

        jLabel4.setText("Gost:");

        jLabel5.setText("Soba:");

        btnIzracunaj.setText("Izracunaj broj dana");
        btnIzracunaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzracunajActionPerformed(evt);
            }
        });

        cmbGost.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbSoba.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A1", "A2", "A3", "B1", "B2", "B3" }));

        txtDatumPrijave.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd.MM.yyyy"))));
        txtDatumPrijave.setText("15.03.2026");
        txtDatumPrijave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDatumPrijaveKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDatumPrijaveKeyTyped(evt);
            }
        });

        txtDatumOdjave.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd.MM.yyyy"))));
        txtDatumOdjave.setText("25.03.2026");
        txtDatumOdjave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDatumOdjaveKeyReleased(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Stavke rezervacije"));

        jLabel6.setText("Usluga:");

        jLabel7.setText("Iznos (din):");

        cmbUsluga.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbUsluga.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbUslugaItemStateChanged(evt);
            }
        });

        btnDodajStavku.setText("Dodaj stavku");
        btnDodajStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajStavkuActionPerformed(evt);
            }
        });

        btnObrisiStavku.setText("Obrisi stavku");
        btnObrisiStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiStavkuActionPerformed(evt);
            }
        });

        tblStavke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblStavke);

        jLabel10.setText("Napomena:");

        txtNapomena.setColumns(20);
        txtNapomena.setRows(5);
        jScrollPane2.setViewportView(txtNapomena);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIznos))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(29, 29, 29)
                                .addComponent(cmbUsluga, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnDodajStavku, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnObrisiStavku, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbUsluga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtIznos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDodajStavku)
                    .addComponent(btnObrisiStavku))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel8.setText("Ukupan iznos:");

        lblUkupanIznos.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblUkupanIznos.setText("0.00");

        jLabel9.setText("Cena po danu:");

        txtCenaPoDanu.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtCenaPoDanu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCenaPoDanuKeyReleased(evt);
            }
        });

        btnIzmeni.setText("Izmeni rezervaciju");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        btnObrisi.setText("Obrisi rezervaciju");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        btnZatvori.setText("Zatvori");
        btnZatvori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZatvoriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(76, 76, 76)
                                .addComponent(cmbSoba, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(79, 79, 79)
                                .addComponent(cmbGost, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel9))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnIzracunaj, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(txtBrojDana, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDatumOdjave)
                            .addComponent(txtDatumPrijave)
                            .addComponent(txtCenaPoDanu, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jLabel8)
                                .addGap(37, 37, 37)
                                .addComponent(lblUkupanIznos))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnZatvori, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnIzmeni, btnObrisi, btnZatvori});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbGost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbSoba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtCenaPoDanu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDatumPrijave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDatumOdjave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(37, 37, 37)
                .addComponent(btnIzracunaj, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtBrojDana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblUkupanIznos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIzmeni)
                .addGap(26, 26, 26)
                .addComponent(btnObrisi)
                .addGap(24, 24, 24)
                .addComponent(btnZatvori)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnZatvoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZatvoriActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnZatvoriActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed

        int rezultat = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da "
                + "obrisete ovu rezervaciju?", "Konfirmacija", JOptionPane.YES_NO_OPTION);

        if (rezultat == JOptionPane.NO_OPTION) {
            return;
        }

        if (rezultat == JOptionPane.YES_OPTION) {
            try {
                KlijentKontroler.getInstance().obrisiRezervaciju(r);
                FormaPretragaRezervacije fp = (FormaPretragaRezervacije) getParent();
                fp.osveziTabelu();
                JOptionPane.showMessageDialog(this, "Uspesno obrisana rezervacija.");
                this.dispose();
            } catch (Exception ex) {
                Logger.getLogger(FormaDetaljiRezervacije.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_btnObrisiActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed

        try {
            if (txtBrojDana.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Morate izracunati broj dana!");
                return;
            }

            String soba = (String) cmbSoba.getSelectedItem();
            SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
            Date datumPrijave = sdf.parse(txtDatumPrijave.getText());
            Date datumOdjave = sdf.parse(txtDatumOdjave.getText());

            ModelTabeleStavkeRezervacije mt = (ModelTabeleStavkeRezervacije) tblStavke.getModel();

            r.setDatumOdjave(datumOdjave);
            r.setDatumPrijave(datumPrijave);
            r.setIznos(ukupanIznos);
            r.setSoba(soba);
            r.setStavkeRezervacije(mt.getLista());

            KlijentKontroler.getInstance().izmeniRezervaciju(r);
            FormaPretragaRezervacije fp = (FormaPretragaRezervacije) getParent();
            fp.osveziTabelu();
            JOptionPane.showMessageDialog(this, "Uspesno izmenjena rezervacija.");
            this.dispose();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
//            Logger.getLogger(FormDetaljiGosta.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void btnIzracunajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzracunajActionPerformed

        ModelTabeleStavkeRezervacije mt = (ModelTabeleStavkeRezervacije) tblStavke.getModel();
        mt.getLista().clear();
        mt.fireTableDataChanged();

        if (txtDatumPrijave.getText().isEmpty() || txtDatumOdjave.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Morate popuniti datum prijave i datum odjave!");
            return;
        }
        
        if (txtCenaPoDanu.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Morate popuniti cenu po danu!");
            return;
        }
        
        
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
            Date datumPrijave = sdf.parse(txtDatumPrijave.getText());
            Date datumOdjave = sdf.parse(txtDatumOdjave.getText());

            if (datumPrijave.after(datumOdjave) || datumPrijave.equals(datumOdjave)) {
                JOptionPane.showMessageDialog(this, "Datum prijave mora biti pre datuma odjave!");
                return;
            }

            if (datumPrijave.before(new Date()) || datumPrijave.equals(datumOdjave)) {
                JOptionPane.showMessageDialog(this, "Datum prijave mora biti u buducnosti!");
                return;
            }

            long razlikaMilisekunde = datumOdjave.getTime() - datumPrijave.getTime();
            long razlika = TimeUnit.DAYS.convert(razlikaMilisekunde, TimeUnit.MILLISECONDS);

            txtBrojDana.setText(String.valueOf(razlika));

            brojDana = Integer.parseInt(txtBrojDana.getText());

            cmbUsluga.setEnabled(true);
            btnObrisiStavku.setEnabled(true);
            btnDodajStavku.setEnabled(true);

            cenaPoDanu = Double.parseDouble(txtCenaPoDanu.getText());

            ukupanIznos = cenaPoDanu * brojDana;

            lblUkupanIznos.setText(String.valueOf(ukupanIznos) + "din");

            Usluga usluga = (Usluga) cmbUsluga.getSelectedItem();
            if (!txtBrojDana.getText().isEmpty()) {
                txtIznos.setText(String.valueOf(usluga.getCena() * brojDana));

            }

        } catch (Exception ex) {
            Logger.getLogger(FormaDetaljiRezervacije.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnIzracunajActionPerformed

    private void txtDatumPrijaveKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDatumPrijaveKeyReleased
        txtBrojDana.setText("");
        ModelTabeleStavkeRezervacije mt = (ModelTabeleStavkeRezervacije) tblStavke.getModel();
        mt.getLista().clear();
        mt.fireTableDataChanged();
        cmbUsluga.setEnabled(false);
        btnObrisiStavku.setEnabled(false);
        btnDodajStavku.setEnabled(false);
        lblUkupanIznos.setText("0.00");
        txtIznos.setText("0.00");
        ukupanIznos = 0;
        brojDana = 0;
    }//GEN-LAST:event_txtDatumPrijaveKeyReleased

    private void txtDatumPrijaveKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDatumPrijaveKeyTyped
        txtBrojDana.setText("");
        ModelTabeleStavkeRezervacije mt = (ModelTabeleStavkeRezervacije) tblStavke.getModel();
        mt.getLista().clear();
        mt.fireTableDataChanged();
        cmbUsluga.setEnabled(false);
        btnObrisiStavku.setEnabled(false);
        btnDodajStavku.setEnabled(false);
        lblUkupanIznos.setText("0.00");
        txtIznos.setText("0.00");
        ukupanIznos = 0;
        brojDana = 0;
    }//GEN-LAST:event_txtDatumPrijaveKeyTyped

    private void txtDatumOdjaveKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDatumOdjaveKeyReleased
        txtBrojDana.setText("");
        ModelTabeleStavkeRezervacije mt = (ModelTabeleStavkeRezervacije) tblStavke.getModel();
        mt.getLista().clear();
        mt.fireTableDataChanged();
        cmbUsluga.setEnabled(false);
        btnObrisiStavku.setEnabled(false);
        btnDodajStavku.setEnabled(false);
        lblUkupanIznos.setText("0.00");
        txtIznos.setText("0.00");
        ukupanIznos = 0;
        brojDana = 0;
    }//GEN-LAST:event_txtDatumOdjaveKeyReleased

    private void cmbUslugaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbUslugaItemStateChanged
        if (cmbUsluga.getSelectedItem() != null) {
            Usluga usluga = (Usluga) cmbUsluga.getSelectedItem();
            if (!txtBrojDana.getText().isEmpty()) {
                txtIznos.setText(String.valueOf(usluga.getCena() * brojDana));
            }
        }
    }//GEN-LAST:event_cmbUslugaItemStateChanged

    private void btnDodajStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajStavkuActionPerformed

        Usluga usluga = (Usluga) cmbUsluga.getSelectedItem();
        double iznos = Double.parseDouble(txtIznos.getText());
        String napomena = txtNapomena.getText();

        StavkaRezervacije si = new StavkaRezervacije(r, -1, napomena,
                usluga.getCena(), iznos, brojDana, usluga);

        ModelTabeleStavkeRezervacije mt = (ModelTabeleStavkeRezervacije) tblStavke.getModel();

        if (mt.postojiUsluga(usluga)) {
            JOptionPane.showMessageDialog(this, "Vec ste uneli ovu uslugu!");
            return;
        }

        mt.dodajStavku(si);

        ukupanIznos = mt.vratiUkupanIznos() + cenaPoDanu * brojDana;
        lblUkupanIznos.setText(String.valueOf(ukupanIznos) + "din");
    }//GEN-LAST:event_btnDodajStavkuActionPerformed

    private void btnObrisiStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiStavkuActionPerformed

        int row = tblStavke.getSelectedRow();

        if (row >= 0) {
            ModelTabeleStavkeRezervacije mt = (ModelTabeleStavkeRezervacije) tblStavke.getModel();
            mt.obrisiStavku(row);

            ukupanIznos = mt.vratiUkupanIznos() + cenaPoDanu * brojDana;
            lblUkupanIznos.setText(String.valueOf(ukupanIznos) + "din");
        }
    }//GEN-LAST:event_btnObrisiStavkuActionPerformed

    private void txtCenaPoDanuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCenaPoDanuKeyReleased
        txtBrojDana.setText("");
        ModelTabeleStavkeRezervacije mt = (ModelTabeleStavkeRezervacije) tblStavke.getModel();
        mt.getLista().clear();
        mt.fireTableDataChanged();
        cmbUsluga.setEnabled(false);
        btnObrisiStavku.setEnabled(false);
        btnDodajStavku.setEnabled(false);
        lblUkupanIznos.setText("0.00");
        txtIznos.setText("0.00");
        ukupanIznos = 0;
        brojDana = 0;
    }//GEN-LAST:event_txtCenaPoDanuKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajStavku;
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnIzracunaj;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnObrisiStavku;
    private javax.swing.JButton btnZatvori;
    private javax.swing.JComboBox cmbGost;
    private javax.swing.JComboBox cmbSoba;
    private javax.swing.JComboBox cmbUsluga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblUkupanIznos;
    private javax.swing.JTable tblStavke;
    private javax.swing.JTextField txtBrojDana;
    private javax.swing.JFormattedTextField txtCenaPoDanu;
    private javax.swing.JFormattedTextField txtDatumOdjave;
    private javax.swing.JFormattedTextField txtDatumPrijave;
    private javax.swing.JTextField txtIznos;
    private javax.swing.JTextArea txtNapomena;
    // End of variables declaration//GEN-END:variables

    private void popuniUsluge() {
        try {
            ArrayList<Usluga> usluge = KlijentKontroler.getInstance().pretragaUsluge();

            cmbUsluga.removeAllItems();

            for (Usluga usluga : usluge) {
                cmbUsluga.addItem(usluga);

            }
        } catch (Exception ex) {
            Logger.getLogger(GlavnaForma.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }

}
